[package]
name = "svg-to-pico"
version = "0.1.0"
edition = "2021"
description = "Convert SVG files to PicoSVG."

[dependencies]
clap = { version = "3.1.10", features = ["cargo"] }
log = "0.4"
env_logger = "0.9"

[dev-dependencies]
assert_cmd = "2.0"
predicates = "2.1"
